name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
  uses: actions/checkout@v2
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
  runs-on: ubuntu-latest
  node-version: '20'


      - name: Set up Python
- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: '3.x'
    node-version: '20'


      - name: Install Dependencies
        run: |
          pip install requests pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile main.py
          mv dist/main main.exe

      - name: Copy Resources
        run: |
          cp config.json main.exe
          cp Icon2022.ico main.exe

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: main-exe
          path: main.exe
